### ISSUE TITLE
[BUG] Image is always considered as change due to compression (on APIM 7.7)

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#112] opened 2019-07-15 14:47 UTC
**Swagger-Promote Version**
1.6.0

**API-Manager and Service-Pack Version**

7.7 
**Expected behavior**
I am running swagger promote script against 7.7 apimanager version,
Below is the output
```
------------------------------------------------------------------------
API-Manager Promote Version: 1.6.0

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote
------------------------------------------------------------------------

0      INFO  nvironmentProperties| Loaded environment properties from file: env.properties.
803    INFO     APIManagerAdapter| API-Manager version is: 7.7.0
909    INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '/opt/axway/pythonscripts/conf/apicreatejson/TESTSWGIMPSCRPT16SSMinimumStayCategory06Rules_transformed.json' (relative path)
911    INFO  IImportConfigAdapter| Handling configured client-applications.
989    INFO  IImportConfigAdapter| Found existing application: 'ATP_ATP_Apps' based on given name 'ATP_ATP_Apps'
1087   INFO     APIManagerAdapter| Found existing API on path: '/services/testswgimpscrpt16ss/v1/rules/record3/cat6' (published) (ID: '557a8079-040b-47d6-98c5-a13d182b21be')
2318   INFO        APIChangeState| Changed property: image[Desired: 'APIImage [bytes=9654]' vs Actual: 'APIImage [bytes=13883]']
2319   INFO     APIManagerAdapter| Strategy: Going to update existing API: TEST SWGIMPSCRPT16SS Minimum Stay (Category 06) Rules (Version: null)
2319   INFO     APIManagerAdapter| Recognized the following changes. Potentially Breaking: [] plus Non-Breaking: [image]
2319   INFO     APIManagerAdapter| Strategy: Update existing API, as all changes can be applied in current state.
2369   INFO     APIManagerAdapter| Updating API-Image from: /opt/axway/apiimages//Ticket.png
2452   INFO     APIManagerAdapter| Default-Application-Quota for API: 'TEST SWGIMPSCRPT16SS Minimum Stay (Category 06) Rules' is UN-CHANGED. Nothing to do.
2452   INFO     APIManagerAdapter| All desired organizations: [ATP_ATP_Org, API Development] have already access. Nothing to do.
2453   INFO     APIManagerAdapter| All desired applications: [[ATP_ATP_Apps]] have already a subscription. Nothing to do.
2456   INFO                   App| Created API-Properties file: '/opt/axway/pythonscripts/conf/apiconfigjson/TESTSWGIMPSCRPT16SSMinimumStayCategory06RulesDetails.prop'
2456   INFO                   App| Successfully replicated API-State into API-Manager
RC: 0
```

I made changes to swagger script to print RC, it is coming as 0, but expecting 10 so I can handle post porcessing only when there are chnages. Now I cannot differentiate between chnaged and unchanged.

**Actual behavior**
RC code coming as 0 when there are no chnages in API

**Test case sample**
> Please describe the steps you have done to replicate the issue
Create API using swagger promote 1.6.0. Rerun the script without any chnages in input config and input json. Expects RC code as 10 but coming it as 0.

**Comment by cwiechmann** [comment] 2019-07-15 15:40
The image is considered as a change. Can you check why? Has the API already an image after the first replication?

**Comment by cwiechmann** [comment] 2019-07-15 16:07
Please not, that the image is conspired as the same when:
- the Hashcode of both images match
- Width & Height are the same AND the color difference is lower than 3 percent.

**Comment by hakila** [comment] 2019-07-15 16:17
Yes, API has image. I did not make any changes. I just reran.

**Comment by hakila** [comment] 2019-07-15 16:18
[XXX@XXX bin]$ ls -l /opt/axway/apiimages//Ticket.png
-rw-r--r-- 1 apigtwsrv apigtwsrv 9654 Jul  1 13:31 /opt/axway/apiimages//Ticket.png
It is always 9654 bytes

**Comment by cwiechmann** [comment] 2019-07-15 16:21
The image is compressed in 7.7 hence you run into that issue. 
Two options: 
Pre-compress the image before you insert it for the first time.
Download the compressed image from the API-Manager and configure it for the API.

**Comment by hakila** [comment] 2019-07-15 16:42
is it not possible to check size before pre-compressing and validate? Images are handled by different team and we are just consumers.

**Comment by cwiechmann** [comment] 2019-07-15 16:44
No, as Swagger-Promote is stateless and doesn’t remember the API it has processed before. 
It needs to get the state for an API from the API-Manager and the manager only returns the compressed image.

**Comment by cwiechmann** [comment] 2019-07-15 17:18
You may share both images (Original & compressed) here. With that I could have a look if I can improve this a bit. Maybe making the threshold which is right now at 3 percent configurable.

**Comment by hakila** [comment] 2019-08-03 23:21
How can i download the compressed image from api manager? I am getting "Save as" which is html file but not the image.
All the time api is recreated even if there are no changes because of this image issue. i am testing default application quota, which used to be 250 mb and changed it to 25 mb. Now the api is not recreated. It just changed the quota to 25 mb. I understand api is not recreated for just default quota changes. Correct me if I am wrong. I expected api to be recreated because of the image . See the output
API-Manager Promote Version: 1.6.1-SNAPSHOT

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote
------------------------------------------------------------------------

0      INFO  nvironmentProperties| Loaded environment properties from file: env.properties.
842    INFO     APIManagerAdapter| API-Manager version is: 7.7.0
972    INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '/opt/axway/pythonscripts/conf/apiswagger/apicreatejson/TESTSWGIMSCRT1                               6SSMinimumStayCategory06Rules_transformed.json' (relative path)
973    INFO  IImportConfigAdapter| Handling configured client-applications.
1029   INFO  IImportConfigAdapter| Found existing application: 'ATP_ATP_Apps' based on given name 'ATP_ATP_Apps'
1129   INFO     APIManagerAdapter| Found existing API on path: '/services/poc/v1/rules/record3/cat6' (published) (ID: '99ce943f-0bef-42a1-9c0a-cc6d72c6c88                               5')
2472   INFO        APIChangeState| Changed property: image[Desired: 'APIImage [bytes=9654]' vs Actual: 'APIImage [bytes=13883]']
2472   INFO        APIChangeState| Changed property: applicationQuota[Desired: 'APIQuota [id=null, type=APPLICATION, restrictions=[QuotaRestriction [api=n                               ull, method=*, type=throttlemb, config={period=hour, per=1, mb=25}]]]' vs Actual: 'APIQuota [id=null, type=APPLICATION, restrictions=[QuotaRestriction [ap                               i=99ce943f-0bef-42a1-9c0a-cc6d72c6c885, method=*, type=throttlemb, config={period=hour, per=1, mb=250}]]]']
2472   INFO     APIManagerAdapter| Strategy: Going to update existing API: TEST SWGIMSCRT16SS Minimum Stay (Category 06) Rules (Version: null)
2472   INFO     APIManagerAdapter| Recognized the following changes. Potentially Breaking: [] plus Non-Breaking: [image, applicationQuota]
2472   INFO     APIManagerAdapter| Strategy: Update existing API, as all changes can be applied in current state.
2521   INFO     APIManagerAdapter| Updating API-Image from: /opt/axway/apidocs/markdown/config/resources/images//Ticket.png
2563   INFO     APIManagerAdapter| Updating Application-Default-Quota for API: TEST SWGIMSCRT16SS Minimum Stay (Category 06) Rules
2781   INFO     APIManagerAdapter| Application-Default quota successfully updated: TEST SWGIMSCRT16SS Minimum Stay (Category 06) Rules
2782   INFO     APIManagerAdapter| All desired organizations: [ATP_ATP_Org, API Development] have already access. Nothing to do.
2783   INFO     APIManagerAdapter| All desired applications: [[ATP_ATP_Apps]] have already a subscription. Nothing to do.
2786   INFO                   App| Created API-Properties file: '/opt/axway/pythonscripts/conf/apiswagger/apiconfigjson/TESTSWGIMSCRT16SSMinimumStayCatego                               ry06Rules_Details.prop'
2786   INFO                   App| Successfully replicated API-State into API-Manager
retCode from swagger script: 0
apiFrontendId: 99ce943f-0bef-42a1-9c0a-cc6d72c6c885

Please explain what is the expected behaviour in this case.

**Comment by hakila** [comment] 2019-08-03 23:24
Also you said image is compressed in 7.7. If you see
Changed property: image[Desired: 'APIImage [bytes=9654]' vs Actual: 'APIImage [bytes=13883]']
Actual is more that desired. Confused with what you said about compressed in 7.7

**Comment by cwiechmann** [comment] 2019-08-04 06:37
I don't exactly know, why the size of the compressed image inside API-Manager is bigger than the actual size. That's unexpected, but the compression is done by the API-Manager and perhaps some strange happens. 

You can download the image of your API using a HTTP-Client, such as Curl:
```
curl -k -u apiadmin:changeme https://<your-api-host>:8075/api/portal/v1.3/discovery/swagger/apis/<your-FE-API-ID>/image --output api-image.jpg
```

Please place both images into a ZIP-Archive and upload it here. I'll create a Unit-Test for the Image-Comparison and try to improve it.

**Comment by cwiechmann** [comment] 2019-08-06 18:30
@hakila, any chance that you share the API-Image you are using here? I would like to complete this bug.

**Comment by hakila** [comment] 2019-08-07 03:37
![api-image-original](https://user-images.githubusercontent.com/17910073/62592944-0b48a100-b8a3-11e9-92ad-ad930473850f.jpg)
![api-image-downloaded](https://user-images.githubusercontent.com/17910073/62592948-0edc2800-b8a3-11e9-9434-2357fdcae77f.jpg)
 Above are the images

**Comment by hakila** [comment] 2019-08-07 03:40
Also did you get a chance to look at below. Pasting from above again for your convenience
All the time api is recreated even if there are no changes because of this image issue. This is known.
New thing I found is when  i am testing default application quota, which used to be 250 mb and changed it to 25 mb. Now the api is not recreated. It just changed the quota to 25 mb. I understand api is not recreated for just default quota changes. Correct me if I am wrong. I expected api to be recreated because of the image . See the output
API-Manager Promote Version: 1.6.1-SNAPSHOT

To report issues or get help, please visit:

https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote
------------------------------------------------------------------------

0      INFO  nvironmentProperties| Loaded environment properties from file: env.properties.
842    INFO     APIManagerAdapter| API-Manager version is: 7.7.0
972    INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '/opt/axway/pythonscripts/conf/apiswagger/apicreatejson/TESTSWGIMSCRT1                               6SSMinimumStayCategory06Rules_transformed.json' (relative path)
973    INFO  IImportConfigAdapter| Handling configured client-applications.
1029   INFO  IImportConfigAdapter| Found existing application: 'ATP_ATP_Apps' based on given name 'ATP_ATP_Apps'
1129   INFO     APIManagerAdapter| Found existing API on path: '/services/poc/v1/rules/record3/cat6' (published) (ID: '99ce943f-0bef-42a1-9c0a-cc6d72c6c88                               5')
2472   INFO        APIChangeState| Changed property: image[Desired: 'APIImage [bytes=9654]' vs Actual: 'APIImage [bytes=13883]']
2472   INFO        APIChangeState| Changed property: applicationQuota[Desired: 'APIQuota [id=null, type=APPLICATION, restrictions=[QuotaRestriction [api=n                               ull, method=*, type=throttlemb, config={period=hour, per=1, mb=25}]]]' vs Actual: 'APIQuota [id=null, type=APPLICATION, restrictions=[QuotaRestriction [ap                               i=99ce943f-0bef-42a1-9c0a-cc6d72c6c885, method=*, type=throttlemb, config={period=hour, per=1, mb=250}]]]']
2472   INFO     APIManagerAdapter| Strategy: Going to update existing API: TEST SWGIMSCRT16SS Minimum Stay (Category 06) Rules (Version: null)
2472   INFO     APIManagerAdapter| Recognized the following changes. Potentially Breaking: [] plus Non-Breaking: [image, applicationQuota]
2472   INFO     APIManagerAdapter| Strategy: Update existing API, as all changes can be applied in current state.
2521   INFO     APIManagerAdapter| Updating API-Image from: /opt/axway/apidocs/markdown/config/resources/images//Ticket.png
2563   INFO     APIManagerAdapter| Updating Application-Default-Quota for API: TEST SWGIMSCRT16SS Minimum Stay (Category 06) Rules
2781   INFO     APIManagerAdapter| Application-Default quota successfully updated: TEST SWGIMSCRT16SS Minimum Stay (Category 06) Rules
2782   INFO     APIManagerAdapter| All desired organizations: [ATP_ATP_Org, API Development] have already access. Nothing to do.
2783   INFO     APIManagerAdapter| All desired applications: [[ATP_ATP_Apps]] have already a subscription. Nothing to do.
2786   INFO                   App| Created API-Properties file: '/opt/axway/pythonscripts/conf/apiswagger/apiconfigjson/TESTSWGIMSCRT16SSMinimumStayCatego                               ry06Rules_Details.prop'
2786   INFO                   App| Successfully replicated API-State into API-Manager
retCode from swagger script: 0
apiFrontendId: 99ce943f-0bef-42a1-9c0a-cc6d72c6c885

**Comment by cwiechmann** [comment] 2019-08-07 05:39
Hi @hakila, Thanks for sharing the images and reason is now clear. The image you provide has originally a transparent background:
![FlightTicketImageOriginalTransparent](https://user-images.githubusercontent.com/16292002/62597169-6d29fa80-b8e5-11e9-969b-be264d7ff869.png)
This is obviously converted by the API-Manager to a white background during import. Due to that the images don't match to each other anymore and that's also the reason, why the API-Image is bigger than the original.
So, my recommendation is to remove transparency from the image before using for an API.

**Comment by cwiechmann** [comment] 2019-08-07 05:44
@hakila, both API-Properties: APIImage & APIQuota are configured in Swagger-Promote like this:
```java
@APIPropertyAnnotation(isBreaking = false, 
writableStates = {IAPI.STATE_UNPUBLISHED, IAPI.STATE_PUBLISHED, IAPI.STATE_DEPRECATED})
protected APIImage image = null;

@APIPropertyAnnotation(isBreaking = false, 
writableStates = {IAPI.STATE_UNPUBLISHED, IAPI.STATE_PUBLISHED, IAPI.STATE_DEPRECATED})	
protected APIQuota applicationQuota = null;
```
The important information is writeableStates and that means, that images and quota can be written to an API in basically all sates. That's the reason, why a changed Quota or Image will never recreate the API.

**Comment by cwiechmann** [comment] 2019-08-07 06:04
I added a white background to your original image: 
![FlightTicketImageOriginal](https://user-images.githubusercontent.com/16292002/62598451-b5e3b280-b8e9-11e9-9496-2758c083131b.png)
And used for an API. It's working as expected:
```
------------------------------------------------------------------------
API-Manager Promote Version: 1.6.1-SNAPSHOT

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote
------------------------------------------------------------------------

0      INFO  nvironmentProperties| Trying to load environment properties from file: env.properties ... not found.
3504   INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: 'samples/petstore.json' (relative path)
3585   INFO     APIManagerAdapter| API-Manager version is: 7.7.0
3989   INFO     APIManagerAdapter| No existing API found exposed on: '/sample/minimal/api/v1'
3990   INFO     APIManagerAdapter| Strategy: No existing API found, creating new!
3994   INFO     APIManagerAdapter| Importing backend API (Swagger/WSDL Import)
5764   INFO     APIManagerAdapter| Create API-Proxy (Front-End API)
8395   INFO     APIManagerAdapter| Ignoring Client-Organizations, as desired API-State is Unpublished!
9174   INFO     APIManagerAdapter| Updating proxy for the following properties: securityProfiles corsProfiles path version name
9360   INFO     APIManagerAdapter| Updating API-Image from: ../images/FlightTicketImageOriginal.png
10214  INFO                   App| Successfully replicated API-State into API-Manager
```
And Re-Running it:
```
------------------------------------------------------------------------
API-Manager Promote Version: 1.6.1-SNAPSHOT

To report issues or get help, please visit:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote
------------------------------------------------------------------------

0      INFO  nvironmentProperties| Trying to load environment properties from file: env.properties ... not found.
3100   INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: 'samples/petstore.json' (relative path)
3131   INFO     APIManagerAdapter| API-Manager version is: 7.7.0
3334   INFO     APIManagerAdapter| Found existing API on path: '/sample/minimal/api/v1' (unpublished) (ID: '01f430ee-033e-46ce-b96c-68a31af8717f')
3656   INFO     APIManagerAdapter| Ignoring Client-Organizations, as desired API-State is Unpublished!
3920   INFO     APIManagerAdapter| Strategy: Going to update existing API: Sample Minimal API (Version: 1.0.0)
3922   WARN                   App| No changes detected between Import- and API-Manager-API
"No changes detected. Existing with RC: 0"
```

**Comment by cwiechmann** [comment] 2019-08-08 13:54
Closing this issue as the reason is now clear.

**Closed by cwiechmann** 2019-08-08 13:54 UTC
Labels: bug

**Comment by hakila** [comment] 2019-08-09 17:49
I did not have any background for the image. In the above uploaded images, first image is the original one (9654 bytes) and the below one is downloaded one from api manager which 13.5 kb. One I used in api creation is transparrent.  Could you please check again why api manager is adding more bytes.

**Comment by cwiechmann** [comment] 2019-08-09 17:53
The original image you are uploading first is transparent. Believe me. See the screenshot which makes it clear. 
Perhaps you don’t see it in the Image-Viewers you are using, as many of them showing a white background instead of the transparency.

**Comment by hakila** [comment] 2019-08-09 18:10
is it not possible to keep the image as is? Why API manager is adding white background? Is it mandatory on your end?

**Comment by cwiechmann** [comment] 2019-08-09 18:14
The API-Manager is doing this, not Swagger-Promote.
As far as I know there is no option in API-Manager to disable it.

**Comment by hakila** [comment] 2019-08-09 18:21
Do I have to open case in axway support for this? Please suggest.

**Comment by cwiechmann** [comment] 2019-08-09 18:27
You can do that, but to be honest, I’m not very confident, that this behavior will be changed very soon. If ever.
From the API-Manager perspective it works as designed, so the only thing you can ask for is to have feature to turn is off. And this feature request will be added to a long list of other more important feature requests.

Better is to use images without a transparent background right from the beginning.
