### ISSUE TITLE
[Help]

### ISSUE THREAD

**Issue by stevebower59** [Axway-API-Management-Plus/apimanager-swagger-promote#174] opened 2019-10-04 16:04 UTC
**Swagger-Promote Version**
1.6.3-SNAPSHOT

**API-Manager and Service-Pack Version**
7.6.2 SP3

**Question**
I am having an issue importing an API that I was able to export with api-export.   

It takes a long time when importing the API and then gives a error saying there was a 500 Internal Server error on the api-manager.  

0      INFO  nvironmentProperties| Trying to load environment properties from file: env.properties ... not found.
2085   INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '..\apis\clone-dhp-onbase-api-v2-document\WBT_OnBase_Download_Clone.json' (relative path)
2235   INFO     APIManagerAdapter| API-Manager version is: 7.6.2 SP3
3180   INFO     APIManagerAdapter| No existing API found exposed on: '/clone/dhp/onbase/api/v2/document'
3180   INFO     APIManagerAdapter| Strategy: No existing API found, creating new!
3195   INFO     APIManagerAdapter| Importing backend API (Swagger/WSDL Import)
3420   INFO     APIManagerAdapter| Create API-Proxy (Front-End API)
130956 ERROR          RestAPICall| Response: 'HTTP/1.1 500 Internal Server Error'
131241 INFO        RollbackAction| Rollback FE-API: 'WBT_OnBase_Download_Clone' (ID: '88944271-5c10-4248-bddf-2e5a1e0e0b16')
131606 INFO       RollbackHandler| Rolled back: '[Frontend-API: true, Backend-API: true]'
131606 ERROR                  App| Error creating API-Proxy. Unexpected response from API-Manager: HTTP/1.1 500 Internal Server Error {"errors":[{"code":500,"message":"Internal server error"}]}. Last request: 'POST POST https://catalogqa.nov.com:443/api/portal/v1.3/proxies/ HTTP/1.1'. Please check the API-Manager traces.

The API was created using a Customer Inbound Security Policy that I thought may be the problem, but I've also tried pass-through as well, and that does not work either.

We're able to export and import the API  using the API Manager.

I've looked at the API Gateway traces, but it does not give much information about what is going on - except that it is importing, and then gets a peer disconnected unexpectedly exception - 

INFO    04/Oct/2019:15:31:04.585 [7806:b865975d915f4f4575e669cc] Importing Swagger 1.1 API 'WBT_OnBase_Download_Clone' for organizationId: 7c7c4575-2c5b-4c55-8e3f-86129eb07856
ERROR   04/Oct/2019:15:31:05.004 [71d0:000000000000000000000000] error handling connection: peer disconnected unexpectedly
ERROR   04/Oct/2019:15:31:05.430 [140e:b965975d935fdee1884e8a84] The message [Id-b965975d935fdee1884e8a84] logged Failure at 10.04.2019 15:31:05,430 with log description: Filter failed
ERROR   04/Oct/2019:15:31:07.007 [71d0:bb65975d945fd569dd52f09c] The message [Id-bb65975d945fd569dd52f09c] logged Failure at 10.04.2019 15:31:07,007 with log description: Filter failed
ERROR   04/Oct/2019:15:31:08.457 [7806:000000000000000000000000] error handling connection: peer disconnected unexpectedly

**Comment by stevebower59** [comment] 2019-10-04 17:11
I tried the same with 1.6.3 and got the following output - but it still failed on import.. 

Not seeing much in trace log


0      INFO  nvironmentProperties| Trying to load environment properties from file: env.properties ... not found.
2235   INFO  IImportConfigAdapter| Reading API-Definition (Swagger/WSDL) from file: '..\apis\clone-dhp-onbase-api-v2-document\WBT_OnBase_Download_Clone.json' (relative path)
2995   INFO     APIManagerAdapter| API-Manager version is: 7.6.2 SP3
4401   INFO     APIManagerAdapter| No existing API found exposed on: '/clone/dhp/onbase/api/v2/document'
4406   INFO     APIManagerAdapter| Strategy: No existing API found, creating new!
4411   INFO     APIManagerAdapter| Importing backend API (Swagger/WSDL Import)
4816   INFO     APIManagerAdapter| Create API-Proxy (Front-End API)
24536  ERROR          RestAPICall| Response: 'HTTP/1.1 502 Bad Gateway'
24736  INFO        RollbackAction| Rollback FE-API: 'WBT_OnBase_Download_Clone' (ID: 'b84abc1a-38e9-488a-9929-3f368e434e00')
25271  INFO       RollbackHandler| Rolled back: '[Frontend-API: true, Backend-API: true]'
25271  ERROR                  App| Error creating API-Proxy. Unexpected response from API-Manager: HTTP/1.1 502 Bad Gateway <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>502 - Web server received an invalid response while acting as a gateway or proxy server.</title>
<style type="text/css">

</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>502 - Web server received an invalid response while acting as a gateway or proxy server.</h2>
  <h3>There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.</h3>
 </fieldset></div>
</div>
</body>
</html>
. Last request: 'POST POST https://catalogqa.nov.com:443/api/portal/v1.3/proxies/ HTTP/1.1'. Please check the API-Manager traces.

**Comment by cwiechmann** [comment] 2019-10-04 17:54
This is typically caused by the API-Manager when trying to download the server-certificates. Please double check that backend-server the Swagger-File or Backend-Basepath is pointing to is really reachable by the API-Manager.
This will be fixed in the upcoming version 7.6.2 SP5 or in 7.7 SP1

**Comment by cwiechmann** [comment] 2019-10-04 17:56
Please keep an eye on the “Bad gateway” error message which is returned by the API-Manager when trying to talk with backend server. This is the root cause.

**Closed** 2019-10-11 10:18 UTC
Labels: help wanted
