### ISSUE TITLE
[BUG] "authenticationProfiles" - SSL :  Cannot validate/fulfill configuration file

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apimanager-swagger-promote#147] opened 2019-09-10 15:23 UTC
**Swagger-Promote Version** : 1.6.2
**Actual behavior**
Erreur at the deployment of an API with an authenticationProfiles SSL. The error : 
```
ERROR                  App| Cannot validate/fulfill configuration file.
com.axway.apim.lib.AppException: Cannot validate/fulfill configuration file.
        at com.axway.apim.swagger.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:191)
        at com.axway.apim.App.run(App.java:181)
        at com.axway.apim.App.main(App.java:44)
Caused by: com.axway.apim.lib.AppException: Can't read Client-Cert-File: /tmp/Delivery_APIM/scripts/swagger-promote/samples/certificates/clientcert.pfx from filesystem or classpath.
        at com.axway.apim.swagger.APIImportConfigAdapter.handleOutboundSSLAuthN(APIImportConfigAdapter.java:764)
        at com.axway.apim.swagger.APIImportConfigAdapter.validateOutboundAuthN(APIImportConfigAdapter.java:715)
        at com.axway.apim.swagger.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:180)
        ... 2 more
Caused by: java.security.KeyStoreException: Uninitialized keystore
        at java.security.KeyStore.aliases(KeyStore.java:1233)
        at com.axway.apim.swagger.APIImportConfigAdapter.handleOutboundSSLAuthN(APIImportConfigAdapter.java:752)
        ... 4 more
```

**Test case sample**
> create a config files : 
```json
{
        "name": "API TEST",
        "path": "/v1/api",
        "state": "published",
        "version": "1.0.0",
        "apiDefinition":"swagger.JSON",
        "organization":"API Development",
        "backendBasepath":"https://test.hostname",
   "authenticationProfiles":[
      {
         "name":"_default",
         "isDefault":true,
         "parameters":{
            "source":"file",
            "certFile":"/tmp/Delivery_APIM/scripts/swagger-promote/samples/certificates/clientcert.pfx",
            "password":"axway",
            "trustAll":true
         },
         "type":"ssl"
      }
]
```

**Comment by cwiechmann** [comment] 2019-09-11 06:59
I tried some things to reproduce the issue you have reported, but no luck. It's working fine on my side. Hence, I made a code review and found the reason, why we don't see the real root-cause.

This is the actual code:
```java
KeyStore store = KeyStore.getInstance(KeyStore.getDefaultType());
try {
	store.load(is, password.toCharArray());
} catch (IOException e) {
	if(e.getMessage().toLowerCase().contains("keystore password was incorrect")) {
		ErrorState.getInstance().setError("Unable to configure Outbound SSL-Config as password for keystore: '"+clientCertFile+"' is incorrect.", ErrorCode.WRONG_KEYSTORE_PASSWORD, false);
		throw e;
	}
}
```
And as you can see, the exception is only properly handled, with an excepted error-message, which is not the one you get. I have fixed that now to that:
```java
KeyStore store = KeyStore.getInstance(KeyStore.getDefaultType());
try {
	store.load(is, password.toCharArray());
} catch (IOException e) {
	if(e.getMessage().toLowerCase().contains("keystore password was incorrect")) {
		ErrorState.getInstance().setError("Unable to configure Outbound SSL-Config as password for keystore: '"+clientCertFile+"' is incorrect.", ErrorCode.WRONG_KEYSTORE_PASSWORD, false);
		throw e;
	} else {
		ErrorState.getInstance().setError("Unable to configure Outbound SSL-Config. Can't load keystore: '"+clientCertFile+"' for any reason.", ErrorCode.UNXPECTED_ERROR, true);
		throw e;
	}
}
```
Please retry with the attached package. 

*Please note*, that you are NOT using 1.6.2 at the moment, as the Stack-Trace told me you are still on 1.6.1-1. 
Please make sure, when updating Swagger-Promote: 
Extracting the files from a new Swagger-Promote version into an old one is not sufficient. The reason is, that JAR-File-Version-Numbers are changing and due to that existing files are not replaced. You end up it JAR-Version conflicts. Best is to extract Swagger-Promote with the given folder and just update the path and symbolic link.
Please check you lib-folder. It must look like this:
![image](https://user-images.githubusercontent.com/16292002/64674661-981de600-d471-11e9-9b29-2bef72b4fc87.png)

Please use this version to see the real error-root-cause and let me know:
[apimanager-swagger-promote-1.6.3-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3599383/apimanager-swagger-promote-1.6.3-SNAPSHOT.zip)

**Comment by Rennaud** [comment] 2019-09-11 07:43
Yes, you are right. The version was 1.6.1-1, it was only pushed on Git but didn't use the one on git for the manual test.
I just tried with the 1.6.3 and now I get this : 

> com.axway.apim.lib.AppException: Cannot validate/fulfill configuration file.
        at com.axway.apim.swagger.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:227)
        at com.axway.apim.App.run(App.java:196)
        at com.axway.apim.App.main(App.java:45)
Caused by: com.axway.apim.lib.AppException: Can't read Client-Cert-File: /tmp/Delivery_APIM/scripts/swagger-promote/samples/certificates/clientcert.pfx from filesystem or classpath.
        at com.axway.apim.swagger.APIImportConfigAdapter.handleOutboundSSLAuthN(APIImportConfigAdapter.java:857)
        at com.axway.apim.swagger.APIImportConfigAdapter.validateOutboundAuthN(APIImportConfigAdapter.java:805)
        at com.axway.apim.swagger.APIImportConfigAdapter.getDesiredAPI(APIImportConfigAdapter.java:216)
        ... 2 more
Caused by: java.io.IOException: Invalid keystore format
        at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:658)
        at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:56)
        at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:215)
        at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:70)
        at java.security.KeyStore.load(KeyStore.java:1445)
        at com.axway.apim.swagger.APIImportConfigAdapter.handleOutboundSSLAuthN(APIImportConfigAdapter.java:835)
        ... 4 more
\>\>\>\> This script is DEPRECATED and will be removed in a future release. Please use 'api-import.bat' instead.

But I don't get why the error is  :  "Invalid keystore format" as we are using the configuration and the certificate from the sample folder.

**Comment by cwiechmann** [comment] 2019-09-11 07:51
I suspect that the file is corrupt. Can you please try to open the Keystore with other tools. 
For instance just double click it on Windows and see if it can read the keystore or use Policy-Studio and try to import it.

**Comment by Rennaud** [comment] 2019-09-11 08:40
Using keytool command : 

> keytool -list -keystore /tmp/Delivery_APIM/scripts/swagger-promote/samples/certificates/clientcert.pfx

here is the return error : 

> keytool error: java.io.IOException: Invalid keystore format

**Comment by Rennaud** [comment] 2019-09-11 08:46
Yo can ignore the last comment, with the option storetype it works.
command : 

> keytool -list -v -keystore /tmp/Delivery_APIM/scripts/swagger-promote/samples/certificates/clientcert.pfx -storetype PKCS12

Text return : 

> Enter keystore password:
Keystore type: PKCS12
Keystore provider: SunJSSE
Your keystore contains 1 entry
Alias name: 1
Creation date: Sep 11, 2019
Entry type: PrivateKeyEntry
Certificate chain length: 1
Certificate[1]:
Owner: EMAILADDRESS=cwiechmann@axway.com, CN=SwaggerPromote, OU=IT, O=Axway, L=Berlin, ST=Berlin, C=DE
Issuer: EMAILADDRESS=cwiechmann@axway.com, CN=SwaggerPromote, OU=IT, O=Axway, L=Berlin, ST=Berlin, C=DE
Serial number: b696b820e264875a
Valid from: Fri Jun 14 09:27:45 CEST 2019 until: Sat Jun 13 09:27:45 CEST 2020
Certificate fingerprints:
         MD5:  05:08:55:D8:5D:7F:0E:14:86:97:63:B8:3E:3C:72:F3
         SHA1: 91:4E:A2:A1:9E:98:8A:0C:87:48:56:8C:14:55:6C:CC:E6:E4:04:F8
         SHA256: 0A:A4:F6:E4:A5:DC:D7:AB:AC:63:45:88:06:94:32:46:AB:6F:1A:58:AD:EA:BA:FF:CE:0C:86:7A:DC:B4:5A:CA
Signature algorithm name: SHA256withRSA
Subject Public Key Algorithm: 2048-bit RSA key
Version: 1
*******************************************
*******************************************

**Comment by cwiechmann** [comment] 2019-09-11 08:56
What is the Java-Version you are using?

**Comment by Rennaud** [comment] 2019-09-11 09:00
It is the one from API Gateway : <installdir_apigtw>/apigateway/Linux.x86_64/jre 

> openjdk version "1.8.0_161"
OpenJDK Runtime Environment (build 1.8.0_161-b14)
OpenJDK 64-Bit Server VM (build 25.161-b14, mixed mode)

**Comment by cwiechmann** [comment] 2019-09-11 09:06
Okay. That's very likely the reason. You are on OpenJDK I'm still using Oracle. Can you please set the Keystore-Type by adding the following Java-Property to the script you use to run Swagger-Promote:
`-Dkeystore.type=pkcs12`

That should look like so:
```
"%JAVA_HOME%\bin\java" -Xms64m -Xmx256m -Dkeystore.type=pkcs12 -classpath "%CLASSPATH%" com.axway.apim.App %*
```

Please note, that with version 1.6.2 I have deprecated run-swagger-import.bat/sh and replaced it with api-import.bat/sh. The goal is to make it consistent with api-export.
I will remove: run-swagger-import in one of the next releases.

**Comment by Rennaud** [comment] 2019-09-11 09:16
Thanks for the note, as I didn't switch to api-import. Just did it to be compliant.

I still have the same error, I tried with your command line but also with : 

> "$JAVA_HOME/bin/java" -Xms64m -Xmx256m -Djavax.net.ssl.keyStoreType=PKCS12 -classpath "$CP" com.axway.apim.App "${@}"

**Comment by cwiechmann** [comment] 2019-09-11 09:17
Okay, let's improve it right now, as it must be improved anyway. The code should be more robust to use the correct Keystore-Type automatically. I'm thinking to implement the following to make it better:
1. Try one by one
Use one know keystore type after the next and see which one passes.
2. Or the user can optionally provide the right keystore type
Like so: "certFile":"/temp2/clientcert.pfx:PKCS12",

What do you think?

**Comment by cwiechmann** [comment] 2019-09-11 11:28
Can you please try with that:
[apimanager-swagger-promote-1.6.3-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3600494/apimanager-swagger-promote-1.6.3-SNAPSHOT.zip)

It now tries to use all supported Keystore-Types or you can overwrite it:
...tes/clientcert.pfx:PKCS12

Unfortunately I couldn't reproduce the issue you have. But maybe this version works for you.

**Comment by Rennaud** [comment] 2019-09-11 11:51
it works only if I overwrite the value : ...tes/clientcert.pfx:PKCS12
In the other case I have this error : 

> 1496   ERROR                  App| Unable to configure Outbound SSL-Config. Can't load keystore: '/tmp/Delivery_APIM/api-manager/swaggers/Horodatage/client-test1-horodatage_aife.interieur.gouv.fr.p12' for any reason. Turn on debug to see log messages.

**Comment by cwiechmann** [comment] 2019-09-11 11:54
Can you please turn on debug and send the me log when not overwriting it?

https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/7.2-Enable-Debug

**Comment by Rennaud** [comment] 2019-09-11 12:14
I had edited my previous comment with the debug.
I put it again here : 
Debug logs :

> 1575 INFO APIDefintion| Used the configured backendBasepath: 'https://qualification.horodatage.interieur.rie.gouv.fr' to adjust the Swagger definition.
1608 DEBUG IImportConfigAdapter| Loading keystore: '/tmp/Delivery_APIM/scripts/swagger-promote/samples/certificates/clientcert.pfx' trying the following types: [JKS, JCEKS, PKCS12, CASEEXACTJKS, DKS]
1609 DEBUG IImportConfigAdapter| Invalid keystore format
1613 DEBUG IImportConfigAdapter| Invalid keystore format
1613 DEBUG IImportConfigAdapter| Stream closed
1614 DEBUG IImportConfigAdapter| Stream closed
1615 DEBUG IImportConfigAdapter| This keystore must be loaded using a DomainLoadStoreParameter
1617 ERROR App| Unable to configure Outbound SSL-Config. Can't load keystore: '/tmp/Delivery_APIM/scripts/swagger-promote/samples/certificates/clientcert.pfx' for any reason. Turn on debug to see log messages.

**Comment by cwiechmann** [comment] 2019-09-11 12:33
Hmm, it looks like, that the Keystore implementation of type: JCEKS is closing the inputstream, hence the next one while iterating over all types fails: 
```
0      INFO  IImportConfigAdapter| Error message using type: JCEKS Error-Message: Invalid keystore format
9968   INFO  IImportConfigAdapter| Error message using type: PKCS12 Error-Message: Stream closed
```

**Comment by cwiechmann** [comment] 2019-09-11 12:49
The best that I came in my mind, was to put JCEKS type to the end of the list.

[apimanager-swagger-promote-1.6.3-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3600819/apimanager-swagger-promote-1.6.3-SNAPSHOT.zip)

This one should work also on your side.

**Comment by Rennaud** [comment] 2019-09-11 12:57
Same error but with this : Error message using type: PKCS12 Error-Message: toDerInputStream rejects tag type -126


> 1485   DEBUG IImportConfigAdapter| Trying to load keystore with keystore type: JKS
1486   DEBUG IImportConfigAdapter| Error message using type: JKS Error-Message: Invalid keystore format
1486   DEBUG IImportConfigAdapter| Trying to load keystore with keystore type: PKCS12
1487   DEBUG IImportConfigAdapter| Error message using type: PKCS12 Error-Message: toDerInputStream rejects tag type -126
1487   DEBUG IImportConfigAdapter| Trying to load keystore with keystore type: CASEEXACTJKS
1487   DEBUG IImportConfigAdapter| Error message using type: CASEEXACTJKS Error-Message: Invalid keystore format
1487   DEBUG IImportConfigAdapter| Trying to load keystore with keystore type: DKS
1488   DEBUG IImportConfigAdapter| Error message using type: DKS Error-Message: This keystore must be loaded using a DomainLoadStoreParameter
1488   DEBUG IImportConfigAdapter| Trying to load keystore with keystore type: JCEKS
1491   DEBUG IImportConfigAdapter| Error message using type: JCEKS Error-Message: Invalid keystore format
1493   ERROR                  App| Unable to configure Outbound SSL-Config. Can't load keystore: '/tmp/Delivery_APIM/scripts/swagger-promote/samples/certificates/clientcert.pfx'' for any reason. Turn on debug to see log messages.

**Comment by cwiechmann** [comment] 2019-09-12 07:23
Hmm, that drives me crazy! Now I changed the implementation in a way, that the Inputstream is re-created on every Keystore-Type. Would you please try on your side as I can't reproduce the issue myself? Thanks!

[apimanager-swagger-promote-1.6.3-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3604190/apimanager-swagger-promote-1.6.3-SNAPSHOT.zip)

**Closed as completed** 2019-09-12 08:33 UTC
Labels: bug
