### ISSUE TITLE
[Feature] Having space characters in the swagger filename

### ISSUE THREAD

**Issue by Rennaud** [Axway-API-Management-Plus/apimanager-swagger-promote#137] opened 2019-08-27 09:47 UTC
**User story**
Swagger's filename is : "swagger api test.json"
Command line :  ./run-swagger-import.sh -a ${swaggerPath}/"swagger api test.json" -c ${swaggerPath}/${swaggerConf}
Error : 1399   ERROR    App| Unable to read Swagger/WSDL file from: /tmp/Delivery_APIM/api-manager/swaggers/Fournisseurs/swagger

**Additional context**
This would avoid a control on filename, as these files are generated by different teams.

**Comment by cwiechmann** [comment] 2019-08-28 06:33
@Rennaud, this is a duplicate to issue #135 which has been fixed already and will be released in the next version. 
For now, you can build your own 1.6.2-SNAPSHOT release as described here: https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/7.1-Contribute-to-this-project#compile-your-own-swagger-promote-release

**Closed by cwiechmann** 2019-08-28 06:33 UTC
Labels: enhancement

**Comment by cwiechmann** [comment] 2019-08-29 06:15
Hi @RadhaR4, The change I made was to change the `schemes` definition in your Swagger-File according to the configured backendBasepath. If you configure this one:
`
backendBasepath=https://ocoesh-kim-test7.centene.com/prweb/PRRestService/HNKIMWebService/KIMWebServices/AddComponent
`
It replaces existing schemes to:
```json
  "schemes": [
    "https"
  ]
```
Please run Swagger-Promote in Debug to see what is really changed in your Swagger-File before it gets imported into the API-Manager. [Enable Debug](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/7.2-Enable-Debug)
Additionally I see, that you have used two different backendBasepath in the Working- and Non-Working-Test. 
Working version:
`https://ccrdworkqueue.dev-rancher.centene.com/nopath`
Non-Working version:
`https://ocoesh-kim-test7.centene.com/prweb/PRRestService/HNKIMWebService/KIMWebServices/AddComponent`
Can you please repeat the test with the same backendBasepath? I want to make sure, that the Backend is really responding, as the error you shared is caused by a Not-Responding backend.
