### ISSUE TITLE
The tool fails to delete old API and doesn't response

### ISSUE THREAD

**Issue by vuvdoan** [Axway-API-Management-Plus/apimanager-swagger-promote#94] opened 2019-07-04 08:01 UTC
Hi,

In some cases (till now I only notices this happens when the version in swagger was changed) the tool has trouble deleting old APIs after new one was created. The tool stays in that state "forever". No exception was thrown.
Either-way I think we need to set timeout for every client requests.

```
[INFO] 'Old' BE-API deleted.
154874 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies  - CookieSpec selected: standard
154874 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies  - Cookie [version: 0][name: APIMANAGERSESSION][value: 5a320823-a6e1-4bb3-aec3-ab98bbdcd11c][domain: xxxxxxxxxxxxxxxxxxxxxx][path: /api/portal/v1.3/][expiry: null] match [(secure)xxxxxxxxxxxxxxxxxxxxxx:443/api/portal/v1.3/proxies/d8ad0d7a-500f-4792-addf-49432b721515]
154874 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies  - Cookie [version: 0][name: APIMANAGERSTATIC][value: a9e1ae6f-5825-49f5-ab1d-01d6bcb99ac1][domain: xxxxxxxxxxxxxxxxxxxxxx][path: /][expiry: null] match [(secure)xxxxxxxxxxxxxxxxxxxxxx:443/api/portal/v1.3/proxies/d8ad0d7a-500f-4792-addf-49432b721515]
154874 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies  - Cookie [version: 0][name: ROUTEID][value: .2][domain: xxxxxxxxxxxxxxxxxxxxxx][path: /][expiry: null] match [(secure)xxxxxxxxxxxxxxxxxxxxxx:443/api/portal/v1.3/proxies/d8ad0d7a-500f-4792-addf-49432b721515]
154874 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache  - Auth cache not set in the context
154875 [main] DEBUG org.apache.http.impl.conn.PoolingHttpClientConnectionManager  - Connection request: [route: {s}->https://xxxxxxxxxxxxxxxxxxxxxx:443][total kept alive: 0; route allocated: 2 of 2; total allocated: 2 of 5]
```

Best regards,
Vu

**Comment by cwiechmann** [comment] 2019-07-04 08:58
@vuvdoan, are you using the latest version?

**Comment by vuvdoan** [comment] 2019-07-04 14:22
@cwiechmann yes. I'm using the maven tool with  axway-swagger-promote-core:1.5.3.. 
One more thing:
I'm publishing multiple APIs with the maven plugin and it is always the last API which fails. There might be some inconsistent states between all of the singletons.

**Comment by cwiechmann** [comment] 2019-07-04 14:58
Thanks for the additional information @vuvdoan. I have the suspicion of some unreleased HTTP-Connection and will look for that.

**Comment by cwiechmann** [comment] 2019-07-05 20:52
Hi @vuvdoan, I made a fix by closing the opened HTTP-Connections, so I think the error shouldn't happen anymore. Unfortunately I couldn't reproduce it on my side, hence I'm asking, if you would be okay to test this?

You can use the latest SNAPSHOT-Version:
```
<dependency>
        <groupId>com.github.axway-api-management-plus.swagger-promote</groupId>
        <artifactId>axway-swagger-promote-core</artifactId>
        <version>1.6-SNAPSHOT</version>
</dependency>
```
```
<repository>
        <id>oss.sonatype.org-snapshot</id>
        <url>http://oss.sonatype.org/content/repositories/snapshots</url>
        <releases><enabled>false</enabled></releases>
        <snapshots><enabled>true</enabled></snapshots>
</repository>
```

Thanks!
Chris

**Comment by vuvdoan** [comment] 2019-07-07 09:22
I ran couple of test cases and it seems to be working fine.  Thanks for fixing it. Btw did you have some performance test on the tool? It seem significantly slower in comparison to 1.5.3 to me.

**Comment by cwiechmann** [comment] 2019-07-08 07:05
Thanks for the info!
Concerning performance, no I don't run specific performance-benchmarks, but I'm always try to improve performance and did this, between the version 1.5.3 and 1.6-SNAPSHOT you have tested with. 
In 1.5.3, to load an existing API two REST-API Calls were performed, now only 1. So, normally it should be faster than slower.

Could you perhaps re-run 1.5.3 with DEBUG enabled and afterwards 1.6-SNAPSHOT? Turn on this DEBUG-Category:
```
  <logger name="com.axway.apim">
	<level value="DEBUG"/>
  </logger>
```
With that I can see the execution times and maybe understand if it's slower and why.

**Comment by vuvdoan** [comment] 2019-07-08 12:21
Yeah..I'll will do that. This bug can be closed. If I find something suspicious regarding the performance, I'll create a new issue.

**Comment by cwiechmann** [comment] 2019-07-12 19:34
Delivered with version 1.6.0

**Closed by cwiechmann** 2019-07-12 19:34 UTC
Labels: bug, done
