### ISSUE TITLE
[BUG] CLI error - Can't create API access requests

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apimanager-swagger-promote#177] opened 2019-10-09 15:43 UTC
**Swagger-Promote Version**
1.6.3

**API-Manager and Service-Pack Version**
7.6.2 SP4

**Expected behavior**
Replication of unpublished APIs (incl. recreating API access for apps)

**Actual behavior**
As soon as I change the API definition file and run the CLI, I get several times the error "Can't create API access requests." After 3or 4 tries, if I run the same CLI call again and it works without any errors!

**Test case sample**
Try to replicate an unpublished API (I only changed the API definition). I will not work the first time, but after 3 or 4 runs using the same configuration.

**Comment by cwiechmann** [comment] 2019-10-15 10:47
Hi @jschaefer77, I tried to replicate this issue, but on my side it's working fine. Are you using an Org-Admin or Admin-Account?

**Comment by jschaefer77** [comment] 2019-10-16 08:57
Hi @cwiechmann,

yes I am using an org admin only. This problem only occurs if I change the swagger file and run CLI tool frequently to update an existing API proxy.

**Comment by cwiechmann** [comment] 2019-11-26 06:59
Hi @jschaefer77, I tried again to reproduce this issue, but again no luck. I'm going to close this issue now as I believe it's some invalid. 
If you encounter the same issue again, please create a new issue with [Debug](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/7.2-Enable-Debug) enabled and share the config file you have used.

**Comment by cwiechmann** [comment] 2019-11-27 05:01
One of the integration tests finally failed on 7.7 SP1 with clientAppsMode set to replace.

**Comment by cwiechmann** [comment] 2019-11-30 07:24
Hi @jschaefer77, 

I have difficulties to reproduce that error and maybe it's already fixed, as I made a number of changes that application handling area. 
Could please try to reproduce that problem with that 1.6.4-SNAPSHOT version and let me know? If you still encounter the issue, please execute with [debug](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/7.2-Enable-Debug) mode enabled, so that I can see why it happens.

[apimanager-swagger-promote-1.6.4-SNAPSHOT.zip](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3906832/apimanager-swagger-promote-1.6.4-SNAPSHOT.zip)

Thanks a lot!

**Comment by cwiechmann** [comment] 2020-01-13 14:51
Closing that issue due to inactivity. Please Re-Open if the error remains.

**Closed by cwiechmann** 2020-01-13 14:51 UTC
Labels: bug
