### ISSUE TITLE
App-Handling failed on API Re-Creation when org is removed

### ISSUE THREAD

**Issue by hakila** [Axway-API-Management-Plus/apimanager-swagger-promote#73] opened 2019-06-02 21:56 UTC
I have api TEST Minimum Stay (Category 06) Rules already defined and published. It has orgs ATP_ATP_Org, X91_91_Org,ATP_CUS_Org and Apps ATP_ATP_Apps, X91_91_App,ATP_CUS_App. But i could not get the image due to bug in 1.5.1.
Now I tried the same API to upload image with 1.5.2 release. In the the cofig file , I have everything same except the orgs and apps. ATP_ATP_Org, X91_91_Org .ATP_ATP_Apps, X91_91_App . If you notice, I dont have ATP_CUS_Org, ATP_CUS_App. I expected the api that was existed before is updated with latest orgs (ATP_ATP_Org, X91_91_Org) and apps (ATP_ATP_Apps, X91_91_App) and with image uploaded. 
It seems it created new api with same name and path but failed with attached error.
If you see the attached log
2938   INFO        APIChangeState| Changed property: applications[Desired: '[[ATP_ATP_Apps], [X91_91_App]]' vs Actual: '[[X91_91_App], [ATP_CUS_App], [ATP_ATP_Apps]]']
 Desired state is correct. But when applying
6101   INFO     APIManagerAdapter| Creating API-Access for the following apps: '[[X91_91_App], [ATP_CUS_App], [ATP_ATP_Apps]]'

Seems there is inconsistency here. As it failed with exception, I assume it could not deleted the old api leaving two apis at the end. Correct me if I am wrong.
[1.5.2 img test issue.txt](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3245281/1.5.2.img.test.issue.txt)
[1.5.2 img test issue.txt](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3245282/1.5.2.img.test.issue.txt)
[1.5.2 img test issue.txt](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3245283/1.5.2.img.test.issue.txt)

**Comment by hakila** [comment] 2019-06-02 22:05
<img width="914" alt="issue73 " src="https://user-images.githubusercontent.com/17910073/58767953-ecefbd80-8560-11e9-884c-e3dc879b0b28.png">

Attaching the api manager ui image showing two apis after running 1.5.2-1 script.

**Comment by hakila** [comment] 2019-06-03 00:19
Also tested same api with no changes in orgs and apps in the existed api . It worked fine and at the end I am left with one api . But if there are changes in orgs and apps , then it is throwing exceptions leaving two apis at the end. This is leading to inconsistent behaviour. Is it possible to fix this asap?

**Comment by hakila** [comment] 2019-06-03 02:27
This is somewhat similar to #56. #56 is failing with 404. This scenario is failing with 400. Is something got broken while fixing #56?

**Comment by cwiechmann** [comment] 2019-06-03 14:20
@hakila, I assume you are running the tool with default-settings for clientAppsMode & clientOrgsMode, both default to "add". Can you confirm this?

**Comment by hakila** [comment] 2019-06-03 15:36
scripts/run-swagger-import.sh -a samples/petstore.json -c samples/minimal-config.json -f true I am invoking like this. I am not sure of default-settings for clientAppsMode & clientOrgsMode? How they can be set?
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/wiki/1.-General-Information does not give those details.

**Comment by hakila** [comment] 2019-06-03 15:38
Just saw the help for the script. Yes , clientAppsMode & clientOrgsMode, both default to "add"

**Comment by cwiechmann** [comment] 2019-06-03 15:41
Okay, in that case I will create an Integration-Test covering your scenario. Let's see if I'm able to reproduce the issue.

**Comment by cwiechmann** [comment] 2019-06-03 15:51
The following must happen in the Test-Case:
1. Create a published API and grant access to 4 orgs and subscribe with 4 Apps
2.1. Simulate a change, which requires a Re-Create of this API (Swagger-File change)
2.2. Additionally remove permission to one org and remove one Client-Apps
Everything running with default clientAppsMode: add & clientOrgsMode: add

Expected behavior: Existing API is re-created and only the smaller set of Orgs & Apps are handled.

**Comment by cwiechmann** [comment] 2019-06-03 16:54
I have created a new Test-Case: UpdateOrgsAndAppsDuringReCreationTestIT.java and with that successfully replicated the problem.

**Comment by hakila** [comment] 2019-06-03 17:04
Glad you were able to reproduce. Also can you give some info on 
 -clientAppsMode <ignore|replace|add>     Controls how configured Client-Applications are treated. Defaults to add!
 -clientOrgsMode <ignore|replace|add>     Controls how configured Client-Organizations are treated. Defaults to add!

I assume add option is to add new orgs and do not do anything with existing. But in this case, it does not behave like add rather it worked like replace. Please give some information on this.

**Comment by cwiechmann** [comment] 2019-06-06 16:06
Created a dedicated branch actually failing due to that issue:
https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/tree/bugfix-issue-58
Needs a fix!

**Comment by cwiechmann** [comment] 2019-07-01 19:23
Released with version 1.5.3

**Closed by cwiechmann** 2019-07-01 19:23 UTC
Labels: bug, done, next release
