### ISSUE TITLE
[Feature] add support to adjust the basePath inside the Swagger-File

### ISSUE THREAD

**Issue by jschaefer77** [Axway-API-Management-Plus/apimanager-swagger-promote#111] opened 2019-07-15 11:11 UTC
With version 1.5.3 a [new feature ](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/issues/81) was introduced. 
This request is similar to adjust in addition to the host as well the basePath in the swagger file.
We are using a chain of gateways. Having the possibility to adjust the basePath in Swagger as well via the API contract file makes it possible for us just to provide only one swagger file, even if we expose the API within a chain of API gateways.

I am not sure why you chose the parameter name backendBasepath if you adjust the host in the swagger?

The following example is a suggestion, how it could look like with customized parameter names:
`{....
"backendHost": "https://example.com",
"backendBasePath": "/test-service/v1"
...}`

backendHost will change the host in the swagger file.
backendBasePath will change the basePath in the swagger file.

What do you think?

**Comment by cwiechmann** [comment] 2019-08-05 19:07
@jschaefer77, yes, good point and makes sense! With that, it would be more consistent.

To ensure backward compatibility I will change the behavior in the following way:
If the configured: backendBasePath can be parsed as a URL (e.g. https://host.abc.com:7878) the host+port is changed as of today. But, additionally I'll log a Warning-Message, that this parameter usage is deprecated, support for that purpose might be removed and instead backendHost and backendBasePath should be used.
If backendBasePath is not a URL, I'll change the behavior as you have described it.

Do you agree with that approach?

**Comment by jschaefer77** [comment] 2019-08-06 08:16
@cwiechmann,

sure, looks good to me. Thanks so far.
I am wondering, if it would make sense to introduce a feature to adjust as well the schema in the Swagger file.
Then it would be possible to control the protocol, host and basePath in an API configuration file. 
E.g. the dev system is only using http and the Q and P systems are using https.
What do you think?

**Comment by cwiechmann** [comment] 2019-08-06 14:19
@jschaefer77, would it also be okay to still have one parameter for that purpose? 
I mean having only:
`{.... , "backendBasePath":"https://example.com:7878/test-service/v1" ...}`
This would be parsed as a URL and replaces host to "example.com:7878" and basePath to: "/test-service/v1".
Having tow different parameters are complicating the code too much. Let me know, if you have any reasons why you would need to distinct parameters.

**Comment by cwiechmann** [comment] 2019-08-06 18:28
Hi @jschaefer77, I have already started to implement the behavior in a way to still have only one parameter: backendBasePath. With the attached version the following happens:

If you set backendBasePath to: 
`https://myhost.customer.com:8767/api/v1/myAPI`
The Swagger-File is changed and contains:
`"host":"myhost.customer.com:8767"`
`"basePath":"/api/v1/myAPI"`

Additionally API-Manager it configured to route requests to: 
`https://myhost.customer.com:8767/api/v1/myAPI`

Can you please let me know, if the feature as it is now implemented in the attached version would be sufficient for your use-case?

[apimanager-swagger-promote-1.6.1-SNAPSHOT.tar.gz](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3473632/apimanager-swagger-promote-1.6.1-SNAPSHOT.tar.gz)

**Comment by jschaefer77** [comment] 2019-08-07 10:56
Hi @cwiechmann,

first of all, for me it is totally okay to have only one parameter for that purpose.
And thank you for providing the snapshot.

I did some tests and got some errors:

- If I run run-swagger-import script in combination with the -s option, the tool always tries to find now an API configuration file with the stage value in the file name
- If run run-swagger-import only with option -c the tool throws an error, because API Manager responded with status code 500.

**Comment by jschaefer77** [comment] 2019-08-07 14:39
Hi @cwiechmann,

why did you close the task. as I wrote I got some errors with the provided snapshot.

**Comment by cwiechmann** [comment] 2019-08-07 14:41
Oh, that was due to the checkin which was saying: Fixes # and then it was automatically closed.

**Comment by cwiechmann** [comment] 2019-08-07 15:48
@jschaefer77, can you check with that this Snapshot-Version again. I have fixed the first issue you reported, but to be honest I'm not fully clear what you mean with the -c only option. 

I checked the following 
`scripts\run-swagger-import.bat -c samples/basic/minimal-config-api-definition.json`
And it works, as long as I have a valid env.properties in the conf-folder containing at least the parameters: username, password & host.
Perhaps the fix I made also fixes the second issue you reported.

Also this SNAPSHOT version contains a fix for the issue #119 you have reported. Feel free to provide feedback for that as well.

[apimanager-swagger-promote-1.6.1-SNAPSHOT.tar.gz](https://github.com/Axway-API-Management-Plus/apimanager-swagger-promote/files/3477821/apimanager-swagger-promote-1.6.1-SNAPSHOT.tar.gz)

**Comment by jschaefer77** [comment] 2019-08-07 17:12
Hi @cwiechmann,

the fix for the first issue works. Thx.
Regarding the second issue, I will try to explain it more in detail. I think I found now the root cause.
By mistake I used the property name backendBasePath instead of backendBasepath which causes the following behavior (because backend host and basePath are not set correctly in the swagger):
- The import tool does not substitute host and basePath in the swagger
- It starts importing backend and frontend API
- API Manager API responds with an error 500 (because it cannot reach backend API host to get the certificates)
- The import tool states now, that it found an existing API on path xyz which is not true and totally confusing.
- The import tool performs a rollback

I have made some screenshots, but I am not able to upload any image to this issue!

You can easily reproduce the problem, if you try to import an API with a wrong hostname in the swagger.

**Comment by cwiechmann** [comment] 2019-08-07 18:42
@jschaefer77, what you have described is the expected behavior. 

If the Swagger-File can't be imported for any reason into the API-Manager (not being able to get the certificates is one), Swagger-Promote should rollback everything to leave API-Manager in a clean-state.
The confusion log-message you see, is coming from the Rollback-Action as it tries to find the API to rollback. I will remove the log-message in case of Rollback, as I agree it is confusing.

FYI: You can turn-off Rollback with the optional parameter: `rollback=false`

**Comment by jschaefer77** [comment] 2019-08-08 07:03
Hi @cwiechmann, thank you for the explanation. I think there is a feature gap in the API Manager REST API itself. If the creation of the frontend API fails, it response only with a error 500 "internal server error", which is not very descriptive. The same problem occurs in the API Manager UI.

When do you plan to release version 1.6.1 including the fix?

**Comment by cwiechmann** [comment] 2019-08-08 07:09
Yes, I do agree. Most of the time the REST-API is responding the error-reason, but not in that API-Proxy-Create-Case. 

I'm working on some improvements for Quota-Management and when this is completed I'll release 1.6.1. maybe today or tomorrow.

**Comment by cwiechmann** [comment] 2019-08-09 10:15
This is fixed in version 1.6.1

**Closed by cwiechmann** 2019-08-09 10:15 UTC
Labels: done, enhancement
